<?php

/**
 * @file
 * Provides hooks for the Local Contexts Integration module.
 */

/**
 * Implements hook_help().
 */
function local_contexts_integration_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.local_contexts_integration':
      return '<p>' . t('Provides integration with the Local Contexts API for displaying Traditional Knowledge Labels.') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function local_contexts_integration_theme() {
  return [
    'local_contexts_block' => [
      'variables' => [
        'title' => '',
        'content' => '',
      ],
      'template' => 'block--local-contexts', // Matches the Twig file name.
    ],
  ];
}